version: '3'
services: 
    web:
        build: .
        env_file:
            - .env
        ports: 
            - "3000:3000"
        volumes:
            - /user/node_modules
            - /usr/src
    test: 